spring:
  application:
    name: jobwise

  datasource:
    url: jdbc:mysql://localhost:3307/jobwise?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # Flyway? ?????? ??
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
#      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-target: build/schema-create.sql
#            create-source: metadata
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
#    baseline-on-migrate: true

  profiles:
    active: local

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace  # ??? ?????? ??
    com.jobwise: debug